// Code generated by protoc-gen-go. DO NOT EDIT.
// source: weatherpb/weather.proto

package weatherpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Weather struct {
	Temperature          float64  `protobuf:"fixed64,1,opt,name=temperature,proto3" json:"temperature,omitempty"`
	TemperatureMin       float64  `protobuf:"fixed64,2,opt,name=temperature_min,json=temperatureMin,proto3" json:"temperature_min,omitempty"`
	TemperatureMax       float64  `protobuf:"fixed64,3,opt,name=temperature_max,json=temperatureMax,proto3" json:"temperature_max,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Found                bool     `protobuf:"varint,5,opt,name=found,proto3" json:"found,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Weather) Reset()         { *m = Weather{} }
func (m *Weather) String() string { return proto.CompactTextString(m) }
func (*Weather) ProtoMessage()    {}
func (*Weather) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b26dc58d367eecd, []int{0}
}

func (m *Weather) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Weather.Unmarshal(m, b)
}
func (m *Weather) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Weather.Marshal(b, m, deterministic)
}
func (m *Weather) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Weather.Merge(m, src)
}
func (m *Weather) XXX_Size() int {
	return xxx_messageInfo_Weather.Size(m)
}
func (m *Weather) XXX_DiscardUnknown() {
	xxx_messageInfo_Weather.DiscardUnknown(m)
}

var xxx_messageInfo_Weather proto.InternalMessageInfo

func (m *Weather) GetTemperature() float64 {
	if m != nil {
		return m.Temperature
	}
	return 0
}

func (m *Weather) GetTemperatureMin() float64 {
	if m != nil {
		return m.TemperatureMin
	}
	return 0
}

func (m *Weather) GetTemperatureMax() float64 {
	if m != nil {
		return m.TemperatureMax
	}
	return 0
}

func (m *Weather) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Weather) GetFound() bool {
	if m != nil {
		return m.Found
	}
	return false
}

type WeatherRequest struct {
	Location             string   `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WeatherRequest) Reset()         { *m = WeatherRequest{} }
func (m *WeatherRequest) String() string { return proto.CompactTextString(m) }
func (*WeatherRequest) ProtoMessage()    {}
func (*WeatherRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b26dc58d367eecd, []int{1}
}

func (m *WeatherRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WeatherRequest.Unmarshal(m, b)
}
func (m *WeatherRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WeatherRequest.Marshal(b, m, deterministic)
}
func (m *WeatherRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WeatherRequest.Merge(m, src)
}
func (m *WeatherRequest) XXX_Size() int {
	return xxx_messageInfo_WeatherRequest.Size(m)
}
func (m *WeatherRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WeatherRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WeatherRequest proto.InternalMessageInfo

func (m *WeatherRequest) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

type WeatherResponse struct {
	Weather              *Weather `protobuf:"bytes,1,opt,name=weather,proto3" json:"weather,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WeatherResponse) Reset()         { *m = WeatherResponse{} }
func (m *WeatherResponse) String() string { return proto.CompactTextString(m) }
func (*WeatherResponse) ProtoMessage()    {}
func (*WeatherResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b26dc58d367eecd, []int{2}
}

func (m *WeatherResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WeatherResponse.Unmarshal(m, b)
}
func (m *WeatherResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WeatherResponse.Marshal(b, m, deterministic)
}
func (m *WeatherResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WeatherResponse.Merge(m, src)
}
func (m *WeatherResponse) XXX_Size() int {
	return xxx_messageInfo_WeatherResponse.Size(m)
}
func (m *WeatherResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WeatherResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WeatherResponse proto.InternalMessageInfo

func (m *WeatherResponse) GetWeather() *Weather {
	if m != nil {
		return m.Weather
	}
	return nil
}

func init() {
	proto.RegisterType((*Weather)(nil), "weather.Weather")
	proto.RegisterType((*WeatherRequest)(nil), "weather.WeatherRequest")
	proto.RegisterType((*WeatherResponse)(nil), "weather.WeatherResponse")
}

func init() { proto.RegisterFile("weatherpb/weather.proto", fileDescriptor_2b26dc58d367eecd) }

var fileDescriptor_2b26dc58d367eecd = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0x89, 0x5a, 0xdb, 0xce, 0x42, 0x2b, 0x83, 0xd0, 0xd0, 0xd3, 0xb2, 0x17, 0x17, 0x91,
	0x0a, 0xf5, 0xec, 0x45, 0xbd, 0x7a, 0x59, 0x11, 0xc1, 0x8b, 0xa4, 0xdb, 0x11, 0x03, 0x6d, 0x12,
	0x93, 0xac, 0xf6, 0x8f, 0xf9, 0xff, 0xa4, 0xd9, 0xdd, 0xb0, 0x90, 0xdb, 0xbc, 0x97, 0x2f, 0x33,
	0x8f, 0x19, 0x58, 0xfc, 0x92, 0xf0, 0x5f, 0x64, 0xcd, 0xe6, 0xb6, 0xab, 0x56, 0xc6, 0x6a, 0xaf,
	0x71, 0xdc, 0xc9, 0xe2, 0x8f, 0xc1, 0xf8, 0xad, 0xad, 0x31, 0x87, 0xcc, 0xd3, 0xde, 0x90, 0x15,
	0xbe, 0xb1, 0xc4, 0x59, 0xce, 0x4a, 0x56, 0x0d, 0x2d, 0xbc, 0x82, 0xf9, 0x40, 0x7e, 0xec, 0xa5,
	0xe2, 0x27, 0x81, 0x9a, 0x0d, 0xec, 0x67, 0xa9, 0x12, 0x50, 0x1c, 0xf8, 0x69, 0x0a, 0x8a, 0xc3,
	0x71, 0xe6, 0x96, 0x5c, 0x6d, 0xa5, 0xf1, 0x52, 0x2b, 0x7e, 0x96, 0xb3, 0x72, 0x5a, 0x0d, 0x2d,
	0xbc, 0x84, 0xd1, 0xa7, 0x6e, 0xd4, 0x96, 0x8f, 0x72, 0x56, 0x4e, 0xaa, 0x56, 0x14, 0x37, 0x30,
	0xeb, 0x62, 0x57, 0xf4, 0xdd, 0x90, 0xf3, 0xb8, 0x84, 0xc9, 0x4e, 0xd7, 0x22, 0xb4, 0x61, 0xa1,
	0x4d, 0xd4, 0xc5, 0x3d, 0xcc, 0x23, 0xed, 0x8c, 0x56, 0x8e, 0xf0, 0x1a, 0xfa, 0x1d, 0x04, 0x3a,
	0x5b, 0x5f, 0xac, 0xfa, 0x15, 0xf5, 0x68, 0x0f, 0xac, 0x5f, 0xe3, 0xb0, 0x17, 0xb2, 0x3f, 0xb2,
	0x26, 0x7c, 0x8c, 0xce, 0x13, 0x79, 0x21, 0x77, 0x0e, 0x17, 0xc9, 0xf7, 0x36, 0xd7, 0x92, 0xa7,
	0x0f, 0x6d, 0x84, 0x87, 0xec, 0x7d, 0x1a, 0xef, 0xb3, 0x39, 0x0f, 0x87, 0xb9, 0xfb, 0x0f, 0x00,
	0x00, 0xff, 0xff, 0x40, 0x65, 0xca, 0xb9, 0xb3, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WeatherServiceClient is the client API for WeatherService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WeatherServiceClient interface {
	WeatherDetails(ctx context.Context, in *WeatherRequest, opts ...grpc.CallOption) (*WeatherResponse, error)
}

type weatherServiceClient struct {
	cc *grpc.ClientConn
}

func NewWeatherServiceClient(cc *grpc.ClientConn) WeatherServiceClient {
	return &weatherServiceClient{cc}
}

func (c *weatherServiceClient) WeatherDetails(ctx context.Context, in *WeatherRequest, opts ...grpc.CallOption) (*WeatherResponse, error) {
	out := new(WeatherResponse)
	err := c.cc.Invoke(ctx, "/weather.WeatherService/WeatherDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WeatherServiceServer is the server API for WeatherService service.
type WeatherServiceServer interface {
	WeatherDetails(context.Context, *WeatherRequest) (*WeatherResponse, error)
}

// UnimplementedWeatherServiceServer can be embedded to have forward compatible implementations.
type UnimplementedWeatherServiceServer struct {
}

func (*UnimplementedWeatherServiceServer) WeatherDetails(ctx context.Context, req *WeatherRequest) (*WeatherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WeatherDetails not implemented")
}

func RegisterWeatherServiceServer(s *grpc.Server, srv WeatherServiceServer) {
	s.RegisterService(&_WeatherService_serviceDesc, srv)
}

func _WeatherService_WeatherDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WeatherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeatherServiceServer).WeatherDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/weather.WeatherService/WeatherDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeatherServiceServer).WeatherDetails(ctx, req.(*WeatherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WeatherService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "weather.WeatherService",
	HandlerType: (*WeatherServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WeatherDetails",
			Handler:    _WeatherService_WeatherDetails_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "weatherpb/weather.proto",
}
